---
id: 201711-organized-around-capabilities
base_name: 201711-organized-around-capabilities
tags:
- rabbit
- microservices
- architecture
- DDD
- bounded context
- team structure
presentation_date: 2017-11-28
version: 2017.11.01.1
licenses:
- MIT
slideshare_id:
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Giovanni Sakti
  email: giosakti@gmail.com
  rubygems_user: giosakti
  slideshare_user:
  speaker_deck_user: giosakti 
